- .travis.yml
- CHANGELOG.rst
- configure
- pyproject.toml
- setup.cfg
* Update configure script to use `python` by default
* Lower build dependency version requirements to support python2
* Lower test dependency version requirements to support python2
* Re-add backports.os as an `installed_requires` dependency
* Add Travis CI support for python 2 + 3
* Update CHANGELOG.rst
Signed-off-by: Steven Esser <sesser@nexb.com>
> Re-Add support for python2

- setup.cfg
- src/commoncode/filetype.py
- src/commoncode/fileutils.py
- tests/commoncode/test_filetype.py
- tests/commoncode/test_fileutils.py
This PR modifies walk(), is_file(), and is_dir() to have the option to follow symlinks. This is needed for the situations where we are forced to deal with symlinked files.
> Modify walk(), is_file(), and is_dir() to have the option to follow symlinks

- setup.cfg
Importing typing causes errors after python 3.6.
See https://github.com/python/typing/issues/573
> Restrict python version for typing dependency

- src/commoncode/resource.py
Deprecated since Python version 3.1, removed in version 3.9
Signed-off-by: Thomas Druez <tdruez@nexb.com>
> Remove encoding keyword argument

- .gitattributes
- CHANGELOG.rst
- src/commoncode/resource.py
- src/commoncode/system.py
- tests/data/resource/virtual_codebase/path_full_root.json
- tests/data/resource/virtual_codebase/stripped-and-skipped-root.json
- tests/test_resource.py
This is a minor version with the addition of a new function in Resource.
> Version v21.4.28

- src/commoncode/resource.py
- tests/data/resource/virtual_codebase/path_full_root.json
- tests/test_resource.py
Signed-off-by: Pratik Dey <pratikrocks.dey11@gmail.com>
Fixes Full root scans in Virtual Codebase
pinging @majurg @pombredanne 
Fixes https://github.com/nexB/scancode-toolkit/issues/2348 / https://github.com/nexB/commoncode/issues/13
> Fixed Full Root scans for Virtual Codebase

- CHANGELOG.rst
- azure-pipelines.yml
- src/commoncode/cliutils.py
- tests/test_cliutils.py
In ScanCode, these
- https://github.com/nexB/scancode-toolkit/issues/2521
- https://github.com/nexB/scancode-toolkit/issues/2529
are reported as issues and are linked to the upgrade of Click when using a pypi pip install (without pinned requirements)
This fixes these issues
> Support Click 8

- src/commoncode/resource.py
- tests/data/resource/virtual_codebase/fingerprint_attribute.json
- tests/test_resource.py
Signed-off-by: Pratik Dey <pratikrocks.dey11@gmail.com>
Fix for #20
> fixed TypeError due to different attributes over directories and files

- CHANGELOG.rst
- src/commoncode/paths.py
- tests/test_paths.py
This PR adds the `preserve_spaces` argument to `commoncode.paths.portable_filename`. When set to True,  `commoncode.paths.portable_filename` will not replace spaces in filenames.
Signed-off-by: Jono Yang <jyang@nexb.com>
> Add preserve_spaces argument to portable_filename

- src/commoncode/resource.py
Adds a new attribute `output_format_version` to the scancode header
to support output data format versioning.
See https://github.com/nexB/scancode-toolkit/issues/2653 for more details.
Signed-off-by: Ayan Sinha Mahapatra <ayansmahapatra@gmail.com>
> Add output data format version to header

- src/commoncode/version.py
get_jar_nv() and get_nupkg_nv() accept a filename of a JAR or nupkg
and return a name/version tuple extracted using multiple heuristics
I added this here for now, as there is a versions module. 
But in the end it would likely best be in ScanCode packagecode module.
It is designed to be used to collect extra info from package archive filenames
and use this to enrich name/versions returned with ScanCode
--package scans
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>
> Add functions to extract name/version of filename

- src/commoncode/cliutils.py
click==8.1.0 [removed](https://click.palletsprojects.com/en/8.1.x/changes/#version-8-1-0) click.get_terminal_size()
> Use shutil.get_terminal_size()

- CHANGELOG.rst
- src/commoncode/paths.py
- tests/test_paths.py
This enables handling safe paths treating some extra characters as safe on POSIX.
In particular this ensures that we can treat the colon ":" as safe for use in file names
on POSIX only. This will allow correct processing of system files in ScanCode.io
and ExtractCode
Reference: https://github.com/nexB/extractcode/issues/41
Reference: https://github.com/nexB/scancode.io/issues/407
Reference: https://github.com/nexB/scancode.io/issues/445
> Make safe filename safe to use on POSIX

- pyproject.toml
- setup.cfg
- src/commoncode/resource.py
- tests/test_resource.py
Signed-off-by: Jono Yang <jyang@nexb.com>
> Do not assign None to codebase attributes #48

- src/commoncode/resource.py
- tests/test_resource.py
This PR fixes a bug in VirtualCodebase creation where in the case where the immediate child of the root has the same directory name as the root would cause us to prevent us from creating the codebase tree properly.
> Fix virtualcodebase creation bug

- src/commoncode/hash.py
Mark our use of MD5 as NOT for security.
> Add support FIPS

- src/commoncode/filetype.py
Closes #61.
Please point out if further changes such as a changelog entry or a corresponding test (there does not seem to be one?) are desired/required.
> Replace the deprecated datetime.datetime.utcfromtimestamp

- requirements.txt
- setup.cfg
- src/commoncode/text.py
Fixes: #79
See: https://git.launchpad.net/beautifulsoup/tree/CHANGELOG#n431
> Adjust `as_unicode` for breaking bs4 4.13 changes

- src/commoncode/hash.py
- tests/test_hash.py
Reference: https://github.com/aboutcode-org/scancode-toolkit/pull/4149/files#r1983173751
> Fix empty file checksum

- src/commoncode/filetype.py
- src/commoncode/fileutils.py
- src/commoncode/resource.py
- tests/test_fileutils.py
@xsuchy Thanks++ for https://github.com/aboutcode-org/commoncode/pull/78
I'm migrating the remaining listdir invocations here.
> Migrate remaining os.listdir to os.scandir

- src/commoncode/fileutils.py
As recommended in https://peps.python.org/pep-0471/
> migrate os.listdir() to os.scandir() to increase performance
